name: Sales Nerd
favicon: null
layout_spectrum: 0.7384676770307124
typography_spectrum: 0.7398317193146795
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2008174709044397
  lightness: 0.7296747765503824
  saturation: 0.8256570107769221
  rhythmicContrast: 0.7256974431220442
purpose: []
