name: Sales Nerd
favicon: null
layout_spectrum: 0.51361
typography_spectrum: 0.38435
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff9966'
    - '#ff0000'
    - '#ff5555'
    - '#ffff00'
    - '#ffbf40'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
